# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane For Android App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor Production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:592775665658:android:165ed8d18bc1487d503643",
        firebase_cli_token:"1//096Ypqci2PEypCgYIARAAGAkSNwF-L9IrBpI8tGNI5TwIN8zaJuExhDal0vvjpviJ9TjhJ7may1j20cq6oUpFHQFBUt_Drsk0Sik",
        android_artifact_type:"APK",
        android_artifact_path:"D:/projects/doctor-appointment/build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "alys1949@hotmail.com""hassan.sherif.200@gmail.com",
        release_notes:"testing the production release with eng hassan mostafa"
      )
  end
end
